### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by chwba** [MackOsmium/Better-2Captcha#1]
Traceback (most recent call last):
  File "/home/admin/PycharmProjects/tool/src/archive/amaranth.py", line 106, in <module>
    response = twocaptcha.solve_recaptcha_v2(google_key="6LeG8gQTAAAAACp5SKFqo0OOUoNhvrkH41M8Mrfz", page_url="https:/www.strawpoll.me/")
  File "/home/admin/PycharmProjects/tool/src/archive/amaranth.py", line 74, in solve_recaptcha_v2
    raise Exception(response.text)
Exception: ERROR_PAGEURL

**Comment by chwba** [comment]
im a retard
